apiVersion: gitops.noctf.dev/v1
kind: ChallengeTemplate
id: 50000000-0000-0000-0000-000000000101
mode: Koh
title: KoH Example
direction: Examples
visibility: Private
statement: statement.md
attachments: []
flags: []
build:
  images:
    - key: hill
      context: runtime
      dockerfile: runtime/Dockerfile
runtime:
  allocation: Shared
  limits:
    memoryBytes: 268435456
    nanoCpus: 500000000
    pidsLimit: 128
  definition:
    kind: Container
    image:
      build: hill
  endpoints:
    - name: public
      protocol: Http
      containerPort: 8080
      exposure: Participants
  controlCheck:
    protocol: Http
    containerPort: 8080
    path: /flag
